FactoryGirl.define do
  factory :rikscha_website_data, class: Hash do
    data do
      { website: {
          domain: 'http://www.rikscha-mainz.de',
          url: [{
                    name: 'http://www.rikscha-mainz.de/Gutscheine/',
                    state: {
                        name: 'state6',
                        readability: { readability: 4.5212887507066,
                                       syllables: 399,
                                       words: 232,
                                       numberOfLinks: 11,
                                       bigwords: 44,
                                       sentences: 61,
                                       language: 'de' },
                        input: { text: [{ id: 'i_fuer',
                                          style: 'width:290px;font-size:20px',
                                          placeholder: 'Beschenkte(r)',
                                          name: 'fuer',
                                          value: nil,
                                          type: 'text' },
                                        { id: 'i_zum',
                                          style: 'width:290px;font-size:20px',
                                          placeholder: 'Anlass',
                                          name: 'zum',
                                          value: nil,
                                          type: 'text' },
                                        { id: 'i_von',
                                          style: 'width:290px;font-size:20px',
                                          placeholder: 'Schenkende(r)',
                                          name: 'von',
                                          value: nil,
                                          type: 'text' },
                                        { id: 'name',
                                          maxlength: 60,
                                          placeholder: 'Vorname Nachname',
                                          name: 'name',
                                          value: nil,
                                          class: 'text',
                                          required: nil,
                                          type: 'text',
                                          size: 424242 },
                                        { id: 'strasse',
                                          maxlength: 60,
                                          placeholder: 'Straße Hausnummer',
                                          name: 'strasse',
                                          value: nil,
                                          class: 'text',
                                          required: nil,
                                          type: 'text',
                                          size: 40 },
                                        { id: 'ort',
                                          maxlength: 60,
                                          placeholder: 'PLZ Ort',
                                          name: 'ort',
                                          value: nil,
                                          class: 'text',
                                          required: nil,
                                          type: 'text',
                                          size: 40 },
                                        { maxlength: 60,
                                          name: 'telefon',
                                          value: nil,
                                          class: 'text',
                                          type: 'text',
                                          size: 40 }],
                                 submit: [{ name: 'action',
                                            value: 'Gutschein bestellen',
                                            onclick: 'return(senden());',
                                            class: 'bold',
                                            type: 'submit' }],
                                 email: [{ id: 'email',
                                           maxlength: 60,
                                           name: 'email',
                                           value: nil,
                                           class: 'text',
                                           required: nil,
                                           type: 'email',
                                           size: 40 }],
                                 textarea: [{ cols: 60, name: 'bemerkung', rows: 5 }],
                                 checkbox: [{ id: 'personalisiert',
                                              name: 'personalisiert',
                                              value: 'personalisiert',
                                              onclick: 'person();',
                                              type: 'checkbox',
                                              checked: true }],
                                 radio: [{ id: 'gutschein_rikschafahrt',
                                           name: 'gutschein',
                                           value: 'Rikschafahrt',
                                           onclick: "gutscheinGewaehlt('Rikschafahrt');",
                                           required: nil,
                                           type: 'radio' },
                                         { id: 'gutschein_mondscheinfahrt',
                                           name: 'gutschein',
                                           value: 'Mondscheinfahrt',
                                           onclick: "gutscheinGewaehlt('Mondscheinfahrt');",
                                           required: nil,
                                           type: 'radio' },
                                         { id: 'gutschein_picknicktour',
                                           name: 'gutschein',
                                           value: 'Picknicktour',
                                           onclick: "gutscheinGewaehlt('Picknicktour');",
                                           required: nil,
                                           type: 'radio' },
                                         { id: 'zahlung_abholung',
                                           name: 'zahlung',
                                           value: 'Abholung',
                                           required: nil,
                                           type: 'radio',
                                           checked: true },
                                         { id: 'zahlung_vorkasse',
                                           name: 'zahlung',
                                           value: 'Vorkasse',
                                           required: nil,
                                           type: 'radio' }] },
                        subject: { words: ['try',
                                           'https',
                                           'com',
                                           'src',
                                           'lt',
                                           'http',
                                           'protocol',
                                           'Fahrtbeginn',
                                           'web',
                                           'write'],
                                   subjects: { Liste__Sprache_: '4',
                                               Portal_Abk: '4',
                                               R: '4',
                                               Begriffskl: '4',
                                               Portal_Kommunikation_als_Thema: '4',
                                               Abk: '4',
                                               Liste__Abk: '4',
                                               Kofferwort: '4',
                                               Zeitliche_Systematik: '4',
                                               Liste: '4',
                                               Einzelwort: '4' },
                                   wordlimit: '20',
                                   classLimit: 18,
                                   language: 'de',
                                   depth: 3 },
                        complexity: { contrast: { _1: { A_tag_With_Low_Contrast: '0',
                                                        TextNodes_With_Low_Contrast: '0',
                                                        paragrahps_with_too_long_lines: '0' } },
                                      vizweb: { numberOfLeaves: 8,
                                                textArea: '0.0092196994357639',
                                                numberOfTextGroups: 1,
                                                visualComplexity: 0.8718767434006,
                                                numberOfImageAreas: 0,
                                                hue: 0.68489074707031,
                                                horizontalSymmetry: '1',
                                                horizontalBalance: 'null',
                                                colorfulness: 12.677470639094,
                                                nontextArea: 0.0015106201171875 },
                                      differenceMatrix: [{ matrix: [0.0,
                                                                    354.49964739052,
                                                                    188.22858443924,
                                                                    271.36322521668,
                                                                    147.80392416983,
                                                                    215.93980642762,
                                                                    325.23376208506,
                                                                    354.49964739052,
                                                                    0.0,
                                                                    166.27687752661,
                                                                    83.138438763306,
                                                                    206.69784711022,
                                                                    138.56406460551,
                                                                    57.0,
                                                                    188.22858443924,
                                                                    166.27687752661,
                                                                    0.0,
                                                                    83.138438763306,
                                                                    40.447496832313,
                                                                    27.712812921102,
                                                                    141.25508840392,
                                                                    271.36322521668,
                                                                    83.138438763306,
                                                                    83.138438763306,
                                                                    0.0,
                                                                    123.56374872915,
                                                                    55.425625842204,
                                                                    68.47627326308,
                                                                    147.80392416983,
                                                                    206.69784711022,
                                                                    40.447496832313,
                                                                    123.56374872915,
                                                                    0.0,
                                                                    68.146900149603,
                                                                    180.33579788827,
                                                                    215.93980642762,
                                                                    138.56406460551,
                                                                    27.712812921102,
                                                                    55.425625842204,
                                                                    68.146900149603,
                                                                    0.0,
                                                                    115.45128842936,
                                                                    325.23376208506,
                                                                    57.0,
                                                                    141.25508840392,
                                                                    68.47627326308,
                                                                    180.33579788827,
                                                                    115.45128842936,
                                                                    0.0],
                                                           palette: [210.0,
                                                                     209.0,
                                                                     207.0,
                                                                     4.0,
                                                                     4.0,
                                                                     4.0,
                                                                     100.0,
                                                                     100.0,
                                                                     100.0,
                                                                     52.0,
                                                                     52.0,
                                                                     52.0,
                                                                     124.0,
                                                                     124.0,
                                                                     122.0,
                                                                     84.0,
                                                                     84.0,
                                                                     84.0,
                                                                     4.0,
                                                                     4.0,
                                                                     61.0] }],
                                      vicramComplexity: 1.1315,
                                      ratios: { pageSize: { pageSize_in_pixel_squared: 1106476,
                                                            pageWidth_in_pixel: 602,
                                                            pageHeight_in_pixel: 1838 },
                                                img_Tag: { img_Area_in_pixel_squared: 756,
                                                           img_document_tag_percentage: 0.068325024672926,
                                                           img_document_tag_ratio: 1463.5925925926 } } },
                        link: { form: [{ formAction: '/Bestellt/' }],
                                a: [{ href: 'http://www.rikscha-mainz.de' },
                                    { plaintext: 'startseite', href: '/' },
                                    { plaintext: 'angebot', href: '/Angebot/' },
                                    { plaintext: 'fuhrpark', href: '/Fuhrpark/' },
                                    { plaintext: 'kontakt', href: '/Kontakt/' },
                                    { plaintext: 'galerie', href: '/Galerie/' },
                                    { plaintext: 'epostkarten', href: '/ePostkarten/' },
                                    { plaintext: 'stellenangebote', href: '/Stellenangebote/' },
                                    { plaintext: 'partner', href: '/Partner/' },
                                    { plaintext: 'impressum', href: '/Impressum/' },
                                    { plaintext: "<span&nbsp;style=\"fo",
                                      href: 'http://m.rikscha-mainz.de' }] },
                        picture: { duration: 3.9,
                                   images: [{ mimetype: 'image/JPEG',
                                              duration: 3.9,
                                              filename: 'random.jpg',
                                              type: 'normal',
                                              geometry: '285x379' },
                                            { mimetype: 'image/PNG',
                                              duration: 0.0,
                                              filename: 'RikschaLogo.png',
                                              type: 'article',
                                              geometry: '135x111' }] } } },
                { name: 'http://www.rikscha-mainz.de/Bild/klein/Galerie/SchlossWaldhausen/',
                  state: { name: 'state59',
                           readability: { readability: 6.6552643905041,
                                          syllables: 287,
                                          words: 163,
                                          numberOfLinks: 21,
                                          bigwords: 44,
                                          sentences: 46,
                                          language: 'de' },
                           subject: { words: ['http',
                                              'protocol',
                                              'com',
                                              'try',
                                              'lt',
                                              'https',
                                              'src',
                                              'jpg',
                                              'write',
                                              'location',
                                              'push'],
                                      subjects: { Liste__Sprache_: '3',
                                                  Portal_Abk: '3',
                                                  R: '3',
                                                  Begriffskl: '3',
                                                  Essen_und_Trinken: '2',
                                                  Portal_Kommunikation_als_Thema: '3',
                                                  Abk: '3',
                                                  Liste__Abk: '3',
                                                  Kofferwort: '3',
                                                  Zeitliche_Systematik: '3',
                                                  Liste: '3',
                                                  Einzelwort: '3' },
                                      wordlimit: '20',
                                      classLimit: 17,
                                      language: 'de',
                                      depth: 3 },
                           complexity: { contrast: { _1: { A_tag_With_Low_Contrast: '0',
                                                           TextNodes_With_Low_Contrast: '0',
                                                           paragrahps_with_too_long_lines: '0' } },
                                         vizweb: { numberOfLeaves: 5,
                                                   textArea: '0',
                                                   numberOfTextGroups: 0,
                                                   visualComplexity: 0.81083171871652,
                                                   numberOfImageAreas: 0,
                                                   hue: 0.73760986328125,
                                                   horizontalSymmetry: '1',
                                                   horizontalBalance: 'null',
                                                   colorfulness: 13.194878004589,
                                                   nontextArea: 0.0023939344618056 },
                                         differenceMatrix: [{ matrix: [0.0,
                                                                       40.706264874095,
                                                                       74.0,
                                                                       27.712812921102,
                                                                       18.0,
                                                                       41.569219381653,
                                                                       13.856406460551,
                                                                       40.706264874095,
                                                                       0.0,
                                                                       40.706264874095,
                                                                       21.748563170932,
                                                                       25.475478405714,
                                                                       21.377558326432,
                                                                       29.546573405388,
                                                                       74.0,
                                                                       40.706264874095,
                                                                       0.0,
                                                                       62.257529665094,
                                                                       56.0,
                                                                       60.431779718953,
                                                                       66.962676171133,
                                                                       27.712812921102,
                                                                       21.748563170932,
                                                                       62.257529665094,
                                                                       0.0,
                                                                       22.715633383201,
                                                                       13.856406460551,
                                                                       13.856406460551,
                                                                       18.0,
                                                                       25.475478405714,
                                                                       56.0,
                                                                       22.715633383201,
                                                                       0.0,
                                                                       34.467375879228,
                                                                       15.099668870541,
                                                                       41.569219381653,
                                                                       21.377558326432,
                                                                       60.431779718953,
                                                                       13.856406460551,
                                                                       34.467375879228,
                                                                       0.0,
                                                                       27.712812921102,
                                                                       13.856406460551,
                                                                       29.546573405388,
                                                                       66.962676171133,
                                                                       13.856406460551,
                                                                       15.099668870541,
                                                                       27.712812921102,
                                                                       0.0],
                                                              palette: [4.0,
                                                                        4.0,
                                                                        4.0,
                                                                        16.0,
                                                                        16.0,
                                                                        41.0,
                                                                        4.0,
                                                                        4.0,
                                                                        78.0,
                                                                        20.0,
                                                                        20.0,
                                                                        20.0,
                                                                        4.0,
                                                                        4.0,
                                                                        22.0,
                                                                        28.0,
                                                                        28.0,
                                                                        28.0,
                                                                        12.0,
                                                                        12.0,
                                                                        12.0] }],
                                         vicramComplexity: 0.3077,
                                         ratios: { pageSize: { pageSize_in_pixel_squared: 175200,
                                                               pageWidth_in_pixel: 400,
                                                               pageHeight_in_pixel: 438 },
                                                   img_Tag: { img_Area_in_pixel_squared: 19194,
                                                              img_document_tag_percentage: 10.955479452055,
                                                              img_document_tag_ratio: 9.1278524538918 } } },
                           link: { a: [{ href: 'http://www.rikscha-mainz.de' },
                                       { plaintext: 'startseite', href: '/' },
                                       { plaintext: 'angebot', href: '/Angebot/' },
                                       { plaintext: 'fuhrpark', href: '/Fuhrpark/' },
                                       { plaintext: 'kontakt', href: '/Kontakt/' },
                                       { plaintext: 'galerie', href: '/Galerie/' },
                                       { plaintext: 'epostkarten', href: '/ePostkarten/' },
                                       { plaintext: 'stellenangebote', href: '/Stellenangebote/' },
                                       { plaintext: 'partner', href: '/Partner/' },
                                       { plaintext: 'impressum', href: '/Impressum/' },
                                       { plaintext: "<span&nbsp;style=\"fo",
                                         href: 'http://m.rikscha-mainz.de' },
                                       { href: '/Bild/klein/Galerie/Picknick/' },
                                       { href: '/Bild/klein/Galerie/Krumelmonster1/' },
                                       { plaintext: 'gross',
                                         href: '/Bild/gross/Galerie/SchlossWaldhausen/' },
                                       { href: '/Bild/klein/Galerie/Picknick/' },
                                       { href: '/Bild/klein/Galerie/Krumelmonster1/' },
                                       { href: '/Bild/klein/Galerie/Picknick/' },
                                       { href: '/Bild/klein/Galerie/Krumelmonster1/' },
                                       { plaintext: 'gross',
                                         href: '/Bild/gross/Galerie/SchlossWaldhausen/' },
                                       { href: '/Bild/klein/Galerie/Picknick/' },
                                       { href: '/Bild/klein/Galerie/Krumelmonster1/' }] },
                           picture: { duration: 0.0 } } },
                { name: 'http://www.rikscha-mainz.de/Bild/klein/Galerie/123/',
                  state: { name: 'state59',
                           readability: { readability: 6.65643905041,
                                          syllables: 28,
                                          words: 123,
                                          numberOfLinks: 21,
                                          bigwords: 24,
                                          sentences: 26,
                                          language: 'de' } } }] } }

    end
  end
end
