language: ruby
cache: bundler
rvm:
  - 2.1.2
  - 2.1.0
  #- jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  #- jruby-head
  #- ree

env:
  #

services:
  #

before_install:
  - gem update --system
  - gem --version

before_script:
  # - bundle exec rake db:setup

script:
  - bundle exec rubocop lib spec -c .rubocop.yml
  - CODECLIMATE_REPO_TOKEN=d88b1f8e253a70c58d685384637fc7b1768fc3fb74dac98c29ca2fb119744c8d bundle exec rake # doing rspec
  - bundle exec rspec

after_script:
  # - bundle exec rake db:setup
